use std::error::Error;

pub fn auth () -> Result<(), Box<dyn Error>> {
    Ok(())
}